export enum REALPOWERMODEDIRECT {
  CHARGE = 'CHARGE',
  DISCHARGE = 'DISCHARGE',
  STAND_BY = 'STAND_BY',
  OPTIMAL = 'OPTIMAL',
  OTHER = 'OTHER',
  MINIMUM = 'MINIMUM',
  MAXIMUM = 'MAXIMUM',
  SOLAR = 'SOLAR',
  SOLAR_GRID = 'SOLAR_GRID',
  GRID = 'GRID',
  BEHIND_METER = 'BEHIND_METER',
}
